### ISSUE TITLE
Error Creating Sink 'graphite'

### ISSUE THREAD

**Issue by venkatakarunakar** [posix4e/GraphiteMetrics2#1]
Hi,

I appreciate the fact that you have written graphite-context which is very helpful. 
I did the same thing which you mentioned, When try to implement metrics2 for hadoop version cdh4.1.2 it's throwing error: Can you help ?

2013-08-21 19:39:15,952 INFO org.apache.hadoop.metrics2.impl.MetricsConfig: loaded properties from hadoop-metrics2.properties
2013-08-21 19:39:15,959 WARN org.apache.hadoop.metrics2.impl.MetricsSystemImpl: Error creating sink 'graphite'
org.apache.hadoop.metrics2.impl.MetricsConfigException: Error creating plugin: org.apache.hadoop.metrics2.graphite.GraphiteContext
    at org.apache.hadoop.metrics2.impl.MetricsConfig.getPlugin(MetricsConfig.java:203)
    at org.apache.hadoop.metrics2.impl.MetricsSystemImpl.newSink(MetricsSystemImpl.java:478)
    at org.apache.hadoop.metrics2.impl.MetricsSystemImpl.configureSinks(MetricsSystemImpl.java:450)
    at org.apache.hadoop.metrics2.impl.MetricsSystemImpl.configure(MetricsSystemImpl.java:429)
    at org.apache.hadoop.metrics2.impl.MetricsSystemImpl.start(MetricsSystemImpl.java:180)
    at org.apache.hadoop.metrics2.impl.MetricsSystemImpl.init(MetricsSystemImpl.java:156)
    at org.apache.hadoop.metrics2.lib.DefaultMetricsSystem.init(DefaultMetricsSystem.java:54)
    at org.apache.hadoop.metrics2.lib.DefaultMetricsSystem.initialize(DefaultMetricsSystem.java:50)
    at org.apache.hadoop.hdfs.server.datanode.DataNode.makeInstance(DataNode.java:1643)
    at org.apache.hadoop.hdfs.server.datanode.DataNode.instantiateDataNode(DataNode.java:1579)
    at org.apache.hadoop.hdfs.server.datanode.DataNode.createDataNode(DataNode.java:1602)
    at org.apache.hadoop.hdfs.server.datanode.DataNode.secureMain(DataNode.java:1755)
    at org.apache.hadoop.hdfs.server.datanode.DataNode.main(DataNode.java:1776)
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.metrics2.graphite.GraphiteContext
    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:247)
    at org.apache.hadoop.metrics2.impl.MetricsConfig.getPlugin(MetricsConfig.java:196)

**Comment by posix4e** [comment]
Are you sure it's in your classpath?

**Comment by venkatakarunakar** [comment]
Yes..

hadoop classpath
/etc/hadoop/conf:/usr/lib/hadoop/lib/_:/usr/lib/hadoop/.//_:/usr/lib/hbase/hbase-0.92.1-cdh4.1.2-security.jar:/usr/lib/hbase:/usr/lib/hbase/lib/zookeeper.jar:/usr/lib/hbase/conf:/usr/lib/hbase/lib/guava-11.0.2.jar:/usr/lib/hadoop/lib/GraphiteContext.jar:/usr/lib/hadoop-hdfs/./:/usr/lib/hadoop-hdfs/lib/_:/usr/lib/hadoop-hdfs/.//_:/usr/lib/hadoop-yarn/.//_:/usr/lib/hadoop-0.20-mapreduce/./:/usr/lib/hadoop-0.20-mapreduce/lib/_:/usr/lib/hadoop-0.20-mapreduce/.//*

**Comment by venkatakarunakar** [comment]
hadoop-metrics2.properties file ::

*.sink.file.class=org.apache.hadoop.metrics2.sink.FileSink
*.period=10

*.sink.graphite.class=org.apache.hadoop.metrics2.graphite.GraphiteContext

# default sampling period

*.period=10
namenode.sink.graphite.servers=graph001:2003
datanode.sink.graphite.servers=graph001:2003
nodemanager.sink.graphite.servers=graph001:2003
resourcemanager.sink.graphite.servers=graph001:2003
secondarynamenode.sink.graphite.servers=graph001:2003

**Comment by posix4e** [comment]
Is file readable by the correct users?

**Comment by venkatakarunakar** [comment]
It has the same permission as all other jars in the hadoop lib directory !

**Comment by posix4e** [comment]
Sorry for repeating myself, how did you generate that classpath printout above?

**Comment by posix4e** [comment]
Also my code should generate
HADOOP_CLASSPATH=/home/posix4e/project/GraphiteMetrics2/target/GraphiteMaven-1.1-SNAPSHOT.jar:

**Comment by posix4e** [comment]
Is that the name of the jar, or did you rename it? Are you sure you have the correct jar

**Comment by venkatakarunakar** [comment]
No Problem 'hadoop classpath' from the terminal..

I created a jar file from the GraphiteContext.java file from your repo by using the following command

jar -cf GraphiteContext.jar GraphiteContext.java

**Comment by posix4e** [comment]
There's your problem. Generate the jar with maven

**Comment by venkatakarunakar** [comment]
ok I'll do that asap and post my results. Thanks.

**Comment by venkatakarunakar** [comment]
Hi posix4e,

I created a jar file using maven. But I see form the logs:

2013-08-21 23:21:03,901 INFO org.apache.hadoop.metrics2.impl.MetricsConfig: loaded properties from hadoop-metrics2.properties
2013-08-21 23:21:03,938 ERROR org.apache.hadoop.metrics2.graphite.GraphiteContext: java.net.ConnectException: Connection refused
2013-08-21 23:21:03,945 INFO org.apache.hadoop.metrics2.impl.MetricsSinkAdapter: Sink graphite started
2013-08-21 23:21:13,974 ERROR org.apache.hadoop.metrics2.graphite.GraphiteContext: java.net.SocketException: Socket is not connected
2013-08-21 23:21:23,967 ERROR org.apache.hadoop.metrics2.graphite.GraphiteContext: java.net.SocketException: Socket is not connected
2013-08-21 23:21:33,970 ERROR org.apache.hadoop.metrics2.graphite.GraphiteContext: java.net.SocketException: Socket is not connected
2013-08-21 23:21:43,970 ERROR org.apache.hadoop.metrics2.graphite.GraphiteContext: java.net.SocketException: Socket is not connected

**Comment by venkatakarunakar** [comment]
any update ? Thanks.

**Comment by posix4e** [comment]
Your graphite isnt up.

sent from mobile
alex newman
4045076749

**Comment by venkatakarunakar** [comment]
Thanks for replying. The graphite server is up and running from long time collecting various metrics. Any more suggestions?

**Comment by posix4e** [comment]
Connect to the hostname and port you specified in your metrics file with
telnet

sent from mobile
alex newman
4045076749

**Comment by venkatakarunakar** [comment]
I'm able to telnet to graphite server on port 2003.

telnet graph001 2003
Trying 10.182.xxxx...
Connected to graph001.
Escape character is '^]'.
^]
telnet> quit
Connection closed.

**Comment by posix4e** [comment]
Bizarre, can you type lsof -i |grep 2003

**Comment by venkatakarunakar** [comment]
you mean on the graphite server or on the datanode ?

**Comment by posix4e** [comment]
the graphite server

**Comment by venkatakarunakar** [comment]
it gives me nothing, but port 2003 is open.

**Comment by posix4e** [comment]
Can you run it as root

**Comment by venkatakarunakar** [comment]
I ran as root !

**Comment by posix4e** [comment]
Perhaps, try
sudo lsof -i|grep carbon
I got
carbon-ca 11266     root    7u  IPv4 257969      0t0  TCP *:cfinger (LISTEN)
carbon-ca 11266     root    8u  IPv4 257970      0t0  TCP *:2004 (LISTEN)
carbon-ca 11266     root    9u  IPv4 257971      0t0  TCP *:afs3-prserver
(LISTEN

**Comment by venkatakarunakar** [comment]
I tried that on the graphite server, but I got nothing, but we run carbon-cache.py script on graphite server in the background on 2004 port which persist metrics to the disk. By any chance if you have a skype ID let me know !

**Comment by posix4e** [comment]
Are you still around?

On Thu, Aug 22, 2013 at 10:56 AM, venkatakarunakar <notifications@github.com

**Comment by posix4e** [comment]
I can do a google hangout

sent from mobile
alex newman
4045076749

**Comment by venkatakarunakar** [comment]
I'm in the office and I cannot do a google hangout now, that's the reason requested for a skype ID !

**Comment by posix4e** [comment]
K im posix4 on skype. You?

sent from mobile
alex newman
4045076749

**Comment by venkatakarunakar** [comment]
I've sent you request..
